### ISSUE TITLE
remove curl

### ISSUE THREAD

**Issue by mcqueenorama** [emicklei/artreyu#2]
Is there any chance of getting rid of curl any time soon?  I don't know if the current net/http has support for the Expect/continue protocol or not.

**Comment by emicklei** [comment]
What a coincidence, I was just reading about that issue on https://github.com/golang/go/issues/3665.  It doesn't seem so. Maybe there is some workaround by someone who created a different http client impl. Have not looked for it yet.

**Comment by emicklei** [comment]
We can try setting the Expect header as it appearantly worked for at least the issue described here http://mail-archives.apache.org/mod_mbox/couchdb-notifications/201505.mbox/%3CJIRA.12833980.1432991518000.73775.1432991537075@Atlassian.JIRA%3E

**Comment by mcqueenorama** [comment]
That's a funny hack.  I wonder if it works in general.  It would be great to get rid of curl and get this thing going with net/http.

**Comment by emicklei** [comment]
I tried this hack and unfortunately, it didn't work.  I got a 413 Request Entity Too Large.

Then I realised that maybe the Nginx machine is the one returning the 413.  So I had a look at the config and saw that the `client_max_body_size` was set to 20m and my artifact size is 31 Mb. So, I changed this setting to 50m and reloaded the config.  Voilà , i got uploaded just fine.

So I tried again with and without the hack (adding the Expect) header. No change, both worked.

**Comment by mcqueenorama** [comment]
So it works without the hack!  Ha, that's pretty cool.  You've got a net/http version working?

**Comment by emicklei** [comment]
yes, and commited

On Mon, Sep 21, 2015 at 7:18 PM, mcqueenorama notifications@github.com
wrote:

> So it works without the hack! Ha, that's pretty cool. You've got a
> net/http version working?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/emicklei/artreyu/issues/2#issuecomment-142047368.

## 

^ Ernest Micklei

http://ernestmicklei.com
